name: Python Wheel Package

on:
  push:
    branches: ["main"]

jobs:
  build-for-jetson:
    if: github.event_name == 'push'
    runs-on: [ARM64]

    container: nvcr.io/nvidia/l4t-jetpack:r36.3.0

    env:
      # Set this to true when using container, false when using self-hosted runner directly
      USE_CONTAINER: true

    steps:
      # Only execute these steps when using a container
      - name: Install core system dependencies
        if: env.USE_CONTAINER == 'true'
        run: |
          apt update
          apt install -y git git-lfs curl wget make cmake build-essential swig python3-dev python3-pip

      - name: Create python symlink
        if: env.USE_CONTAINER == 'true'
        run: |
          ln -sf /usr/bin/python3 /usr/bin/python

      # Steps that run regardless of container usage
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python version
        run: |
          python --version
          which python
          python -c "import sys; print(sys.executable)"
          python -c "import sysconfig; print('Include path:', sysconfig.get_path('include'))"

      - name: Install python build dependencies
        run: |
          python -m pip install wheel Cython

      - name: Compile and build wheel
        env:
          # Pass the run number as an environment variable
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          python cythonizer.py -s src
          python setup.py bdist_wheel

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autolife_robot_kiosk-wheel
          path: dist/*.whl